create table public.assets (
  id uuid not null default gen_random_uuid (),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  name text not null,
  description text null,
  bucket_name text not null,
  storage_path text not null,
  public_url text null,
  file_name text not null,
  file_extension text null,
  mime_type text null,
  file_size numeric null,
  width integer null,
  height integer null,
  folder text null,
  category text null,
  tags text[] null default '{}'::text[],
  is_public boolean not null default false,
  is_active boolean not null default true,
  metadata jsonb null default '{}'::jsonb,
  constraint assets_pkey primary key (id),
  constraint assets_storage_path_key unique (storage_path)
) TABLESPACE pg_default;